name: cve-2023-41080

services:
  tomcat-9-0-79:
    image: tomcat:9.0.79
    ports:
      - 8081:8080
    volumes:
      - ./webapps/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./conf/web.xml:/usr/local/tomcat/conf/web.xml

  tomcat-9-0-80:
    image: tomcat:9.0.80
    ports:
      - 8082:8080
    volumes:
      - ./webapps/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./conf/web.xml:/usr/local/tomcat/conf/web.xml
